### PR TITLE
The Load API

### PR DESCRIPTION
**Pull request by rrbutani**
<TODO>

### CODE REVIEW

**Comment by rrbutani** [comment]
An old comment that's probably worth putting somewhere:

```rust
    // We debated a bit on whether the address here should be a u8 (page offset)
    // or a Word (full address).
    //
    // The argument for having a page offset is smaller messages and being able
    // to avoid another error case.
    //
    // The argument for full address is additional safety; in case the host
    // unwittingly sends a Word from another page, we'll catch it.
    //
    // Another consideration is how to handle non-aligned `Word`s. One way to do
    // this is to just discard them. Another is represent the chunk as an array
    // of Options (downside is message size). Yet another is to error on any
    // unaligned calls. And finally, we could error only on those unaligned
    // calls that result in us crossing a page boundary.
    //
    // Ultimately, we really do expect this to only be used for flashing so
    // we don't really care all that much that it's hard to write to pieces of
    // memory smaller than a chunk (to preserve the contents that are already
    // in, for example, 6 of the 8 Words in a chunk, you'd have to read those
    // memory locations first — this kind of situation never arises when
    // flashing a program). Additionally since the semantics of these calls are
    // that the page is assumed to be empty when `start_write_page` is called,
    // the only users might want to have persist is data that was sent since
    // the last `start_write_page` call; i.e. data that the user just sent us!
    //
    // So, we'll take a chunk that must have 8 specified Words and we'll error
    // if the chunk spans the correct page and another page.
```

**Comment by rrbutani** [comment]
This is also worth highlighting:

```rust
 #[derive(Clone)] // This compromises our API. Unfortunately it's easier to offer                                                                                                            
                  // this impl than to redo Encoding's Decode to move the values                                                                                                             
                  // it encodes (doing so would also possibly hurt performance).                                                                                                             
                  //                                                                                                                                                                         
                  // We also already offer this escape hatch (kind of) since we                                                                                                              
                  // offer Serialize and Deserialize impls for this type.                                                                                                                    
                  //                                                                                                                                                                         
                  // So, it'll just have to be another thing users who call the                                                                                                              
                  // unsafe constructor have to keep track of.
```

**Review by jerryyang98 — APPROVED** [review]
Merge

**Review by gipsond — APPROVED** [review]
All seems fine by me. Interesting how you used generics to force the load session to proceed in a specific order. I might've just passed `Offset` or `PageIndex` as parameters and trusted the user a little more (not to say it doesn't make sense in this situation to enforce it).

**Comment by rrbutani** [comment]
> All seems fine by me. Interesting how you used generics to force the load session to proceed in a specific order. I might've just passed `Offset` or `PageIndex` as parameters and trusted the user a little more (not to say it doesn't make sense in this situation to enforce it).

yup! this is what Amr and I were talking about 3 or 4 weeks ago

This isn't a great example case for it (because, as mentioned in the comments and in the commits there are still a couple of holes — the one I still remember is that one of the types needed to impl Clone because our transport setup passes by value for send or something; also that you can interleave load API function calls with other calls if you don't use the provided function) but the typestate pattern is always super nifty. [This](https://github.com/Munksgaard/session-types) _is_ a good shiny example case.

Regardless, I still maintain that it's a good addition since it vastly reduces the weird failure cases that we have to deal with device side.

**Pull request merged**
