### PR TITLE
bench: add an i/o benchmark and add lc3tools to the benchmarks

### LINKED ISSUE #114: Add LC3Tools to the benchmarks
### what
Add LC3Tools to the benchmarks.

### steps
 - [x] make Rust bindings for LC3Tools: [rrbutani/lc3tools-sys](//github.com/rrbutani/lc3tools-sys)
 - [x] add LC3Tools to the existing benchmarks (speed, overhead)
 - [x] add an I/O benchmark

### where
branch: [`imp-lc3tools-benchmarks`](//github.com/ut-utp/core/tree/imp-lc3tools-benchmarks)

### open questions
None, yet.

### PR DESCRIPTION
**Pull request by rrbutani**
This ended up doing a few other things including:
  - adding the "don't switch to user mode if the starting address is <`0x3000`" thing that we've been meaning to add to the OS
  - fixing a couple of bugs in the `InputShim`

Both of these things could use some more attention down the road (some tests for the former and some clean up for the latter).

Everything else in this PR actually is just for the benchmarks.

Closes #114.

### CODE REVIEW

**Comment by gipsond** [comment]
Need to take a second look at this later after reviewing `Input` and `InputShim`. Everything seems fine to me style-wise.

**Comment by rrbutani** [comment]
@gipsond Can you take a look at this sometime this week?

**Review by gipsond — APPROVED** [review]
lgtm. Nice catch. If you have time, adding the I/O tests mentioned in the TODO would be good, but
1. those aren't really part of this PR
2. time...

so I get it.

**Comment by rrbutani** [comment]
Right, sorry. I'll add in tests for it once I get to doing cleanup. Soon, hopefully.

**Pull request merged**
